// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademia.Models;

#nullable disable

namespace SistemaAcademia_2._0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124174806_AdicionaDiarioTreino")]
    partial class AdicionaDiarioTreino
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SistemaAcademia.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("SistemaAcademia.Models.ItemTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repeticoes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoDescanso")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId");

                    b.ToTable("ItensTreino");
                });

            modelBuilder.Entity("SistemaAcademia.Models.RegistroItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistroTreinoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepeticoesRealizadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesRealizadas")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("RegistroTreinoId");

                    b.ToTable("RegistrosItens");
                });

            modelBuilder.Entity("SistemaAcademia.Models.RegistroTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataTreino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<int>("TreinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TreinoId");

                    b.ToTable("RegistrosTreino");
                });

            modelBuilder.Entity("SistemaAcademia.Models.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("SistemaAcademia.Models.ItemTreino", b =>
                {
                    b.HasOne("SistemaAcademia.Models.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademia.Models.Treino", "Treino")
                        .WithMany("ItensTreino")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("SistemaAcademia.Models.RegistroItem", b =>
                {
                    b.HasOne("SistemaAcademia.Models.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademia.Models.RegistroTreino", "RegistroTreino")
                        .WithMany("ItensRegistrados")
                        .HasForeignKey("RegistroTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("RegistroTreino");
                });

            modelBuilder.Entity("SistemaAcademia.Models.RegistroTreino", b =>
                {
                    b.HasOne("SistemaAcademia.Models.Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("SistemaAcademia.Models.RegistroTreino", b =>
                {
                    b.Navigation("ItensRegistrados");
                });

            modelBuilder.Entity("SistemaAcademia.Models.Treino", b =>
                {
                    b.Navigation("ItensTreino");
                });
#pragma warning restore 612, 618
        }
    }
}
